name: upload_image
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  camera: ^0.10.0+1
  camera_windows: ^0.2.1+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
