name: quote_list_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  provider: ^6.0.4

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/
