name: quote_list_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.7.0
  provider: ^6.0.4

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
